apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-a
  namespace: mongoexpress-namespace
spec:
  ingressClassName: nginx
  rules:
  - host: saidomain.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express-ingress-service
            port:
              number: 80